name: Build and Deploy

on:
  push:
    branches: [main]
    tags:
      - "v*" # 添加这一行，以便在推送标签时触发 Release 作业

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          token: ${{ secrets.GH_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.24" # 您的 Go 版本

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Go modules
        run: go mod download

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # 您的 Node.js 版本

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: assets/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('assets/pnpm-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install pnpm
        run: npm install -g pnpm@10

      - name: Install Frontend
        run: |
          cd assets # 前端代码目录
          pnpm install

      - name: Build Frontend
        run: |
          cd assets # 前端代码目录
          pnpm run build

      - name: Cross-compile for Linux amd64
        run: GOOS=linux GOARCH=amd64 go build -o yuyu-album-linux-amd64

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yuyu-album-linux-amd64
          path: yuyu-album-linux-amd64

      - name: Cross-compile for Windows amd64
        run: GOOS=windows GOARCH=amd64 go build -o yuyu-album-windows-amd64.exe

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yuyu-album-windows-amd64.exe
          path: yuyu-album-windows-amd64.exe

      - name: Cross-compile for macOS amd64
        run: GOOS=darwin GOARCH=amd64 go build -o yuyu-album-macos-amd64

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yuyu-album-macos-amd64
          path: yuyu-album-macos-amd64

  release:
    runs-on: ubuntu-22.04
    needs: build # 确保在 build 作业完成后再运行
    if: startsWith(github.ref, 'refs/tags/v') # 仅当是标签推送时才运行此作业

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 需要再次检出代码，以便访问工作目录

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: yuyu-album-linux-amd64
          path: . # 下载到当前目录

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: yuyu-album-windows-amd64.exe
          path: . # 下载到当前目录

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: yuyu-album-macos-amd64
          path: . # 下载到当前目录

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            yuyu-album-linux-amd64
            yuyu-album-windows-amd64.exe
            yuyu-album-macos-amd64
          body: |
            ✨ 新版本发布！
            🎉 这个版本包含了针对 Linux, Windows 和 macOS 的可执行文件。
            # 您可以在这里添加更多关于 Release 的描述。
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub 提供的默认 token
